### ISSUE TITLE
Get Order Detail (For Apotek)

### ISSUE THREAD

**Issue by ichakid** [CatalinaID/tokobat-api#14]
Request:
orderID

Response:
Order

Ngubah status read di backend

**Comment by alifanuraniputri** [comment]
Contoh:

## SUCCESS

[GET] .../tokobat-api/transactions/detail?id=1

Response:

{
    "name": "obat alida",
    "id": 0,
    "total": 10000,
    "status": "1",
    "description": null,
    "user": {
        "name": "alifa",
        "id": 1,
        "session": null,
        "msisdn": "081910355420",
        "uid": "357072061795934",
        "dateCreate": 1454832406654
    },
    "apotek": {
        "address": null,
        "name": "Apotek Ganesha",
        "id": 1,
        "hash": "b3894524eaf9809bd4f3ad2ff06fa4ab8d9251d3",
        "username": "apotek_ganesha",
        "salt": "vmivkh8d3tbfnap12tq7kfdmtr",
        "balance": 0,
        "lat": "-6.89148",
        "lng": "107.6106591",
        "dateCreate": 1454832325987
    },
    "notes": "tidak ada",
    "dateCreate": 1454832406654,
    "readBy": true,
    "imgPath": "img",
    "apotekNotes": "coba",
    "message": "OK"
}

## INVALID ID

[GET] .../tokobat-api/transactions/detail?id=2

Response:

{
    "name": null,
    "id": 0,
    "total": null,
    "status": null,
    "description": null,
    "user": null,
    "apotek": null,
    "notes": null,
    "dateCreate": null,
    "readBy": false,
    "imgPath": null,
    "apotekNotes": null,
    "message": "FAIL"
}
