### ISSUE TITLE
Login User without E-Cash

### ISSUE THREAD

**Issue by ichakid** [CatalinaID/tokobat-api#15]
## SUCCESS

[POST] .../tokobat-api/apotek/login?username=hayyu&password=hayyyyy

Response:200
{
    "name": "Hayyu LH",
    "message": "Success",
    "id": 1
}
## SALAH PWD

[POST] .../tokobat-api/apotek/login?username=hayyu&password=password

Response: 401
{
    "name": null,
    "message": "Username and password don't match",
    "id": 0
}
## NOT USER

[POST] .../tokobat-api/users/login?username=notuser&password=password

Response: 404
{
    "name": null,
    "message": "Username not registered",
    "id": 0
}
## BAD PARAM

[POST] .../tokobat-api/users/login?username=user&password=

Response: 400
{
    "name": null,
    "message": "Username or password is empty",
    "id": 0
}

**Comment by alifanuraniputri** [comment]
@ichakid 

http://tokobat-api.mybluemix.net/users/login?username=alifanuraniputri&password=milikalifa

Response with 

{
    "name": null,
    "message": "Username not registered",
    "id": 0
}

**Comment by ichakid** [comment]
Solved. Salah di UserDaoImpl:findByUsername
