### ISSUE TITLE
Login untuk Apotek

### ISSUE THREAD

**Issue by ichakid** [CatalinaID/tokobat-api#2]
Request:
apotekID
password

Response:
success

**Comment by alifanuraniputri** [comment]
Contoh:

## SUCCESS

[POST] .../tokobat-api/apotek/login?username=apotek_plesiran&password=apotek_plesiran

Response:

{
    "name": "Apotek Plesiran",
    "message": "success",
    "id": 3,
    "code": 0
}

## SALAH PWD

.../tokobat-api/apotek/login?username=apotek_plesiran&password=apotek_plesiran1

Response:

{
    "name": "Apotek Plesiran",
    "message": "invalid",
    "id": 3,
    "code": 1
}

## NOT USER

.../tokobat-api/apotek/login?username=apotek_plesiran1&password=apotek_plesiran1

Response:

{
    "name": null,
    "message": "error",
    "id": 0,
    "code": 1
}

**Comment by afik** [comment]
kak. code nya kebalik ya? kalo sukses 1 kalo failed 0

**Comment by afik** [comment]
kalo aku mau minta dia sukses 200 ga sukses 400 boleh ngga? wkwkwk _kalo ga juga gpp sih_

**Comment by alifanuraniputri** [comment]
Hello afik. Jadi itu id bukan kode. Default response balikin message n id.
Klo failed id nya pke default which is 0

**Comment by afik** [comment]
oalah, jadi bedain sukses login sama engga kalo code nya ga 0 ya

**Comment by alifanuraniputri** [comment]
messagenya aja fik, ya sama aja sih

2016-02-21 23:20 GMT+07:00 Khoirunnisa Afifah notifications@github.com:

> oalah, jadi bedain sukses login sama engga kalo code nya ga 0 ya
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CatalinaID/tokobat-api/issues/2#issuecomment-186853512
> .

## 

Alifa Nurani Putri
Teknik Informatika ITB 2011

**Comment by alifanuraniputri** [comment]
@afik 

the password is "milikalifa"
