### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by ichakid** [CatalinaID/tokobat-api#3]
Request:
nama

**Comment by alifanuraniputri** [comment]
Contoh:

## SUCCESS

[POST] .../tokobat-api/users/register?name=alifa&msisdn=081910355420

Response:

{
    "name": "alifa",
    "session": null,
    "uid": "357072061795934",
    "msisdn": "081910355420",
    "message": "OK",
    "id": 1
}

## NOT REGISTERED MSISDN

[POST] .../tokobat-api/users/register?name=alifa&msisdn=081910355470

Response:

{
    "name": null,
    "session": null,
    "uid": null,
    "msisdn": null,
    "message": "FAIL",
    "id": 0
}

**Comment by ichakid** [comment]
atribut usernya berubah. Jadi registernya: username, name, password

**Comment by alifanuraniputri** [comment]
Contoh:

## SUCCESS

[POST] .../tokobat-api/users/register?username=alifanuraniputri4&name=alifa&password=milikalifa

Response:

{
    "name": "alifa",
    "username": "alifanuraniputri3",
    "message": "OK",
    "id": 0
}

## ERROR

[POST] .../tokobat-api/users/register?username=alifanuraniputri&name=alifa&password=milikalifa

Response:
{
    "name": null,
    "username": null,
    "message": "FAIL",
    "id": 0
}
