### ISSUE TITLE
Order Resep

### ISSUE THREAD

**Issue by ichakid** [CatalinaID/tokobat-api#4]
Request:
id user
title
gambar
apotekID
catatan
deskripsi

Response:
orderID

status awal: waiting

**Comment by alifanuraniputri** [comment]
Request

opsional params: imgPath, catatan, deskripsi

[POST] .../tokobat-api/transactions/order?name=obat 2&userId=1&apotekId=1

Response

{
    "name": "obat 2",
    "id": 0,
    "total": null,
    "description": null,
    "status": null,
    "apotekNotes": null,
    "imgPath": null,
    "notes": null,
    "readBy": false,
    "dateCreate": null,
    "user": {
        "name": "alifa",
        "id": 1,
        "session": null,
        "msisdn": "081910355420",
        "dateCreate": 1454832406654,
        "uid": "357072061795934"
    },
    "apotek": {
        "address": null,
        "name": "Apotek Ganesha",
        "id": 1,
        "hash": "b3894524eaf9809bd4f3ad2ff06fa4ab8d9251d3",
        "salt": "vmivkh8d3tbfnap12tq7kfdmtr",
        "username": "apotek_ganesha",
        "balance": 0,
        "lng": "107.6106591",
        "lat": "-6.89148",
        "dateCreate": 1454832325987
    },
    "message": "OK"
}

**Comment by alifanuraniputri** [comment]
to be add uploading file

**Comment by ichakid** [comment]
eh, ini gak papa hash dan salt-nya dikeluarin? balance-nya gak perlu kayaknya
