### ISSUE TITLE
Get All Orders (for Apotek)

### ISSUE THREAD

**Issue by ichakid** [CatalinaID/tokobat-api#5]
Request:
ApootekID

Response:
List of Pengirim
List of Status Order

**Comment by ichakid** [comment]
## KOSONG

[GET] .../tokobat-api/transactions?apotekId=100

Response:
{
    "transactions": [],
    "total": 0
}

## ISI

[PUT] .../tokobat-api/transactions?apotekId=1

Response:
{
    "transactions": [
        {
            "transId": 1,
            "senderName": "Hayyu",
            "read": false
        },
        {
            "transId": 2,
            "senderName": "Hayyu",
            "read": false
        },
        {
            "transId": 3,
            "senderName": "Hayyu",
            "read": false
        }
    ],
    "total": 3
}

**Comment by afik** [comment]
kalo aku minta date_create dibalikin juga boleh ga? wkwk. biar di tabel bisa ditampilin, kemaren ga kepikiran euy

**Comment by alifanuraniputri** [comment]
Oke kapan2 ya wkwk

**Comment by ichakid** [comment]
type/format date_create mau kayak gimana fik? 
kayak gini atau format lain? "dateCreate": 1456052652124

**Comment by alifanuraniputri** [comment]
ya timestamp aja, d angular gampang inih formatting tanggal

2016-02-22 1:11 GMT+07:00 Choirunnisa Fatima notifications@github.com:

> type/format date_create mau kayak gimana fik?
> kayak gini atau format lain? "dateCreate": 1456052652124
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CatalinaID/tokobat-api/issues/5#issuecomment-186875821
> .

## 

Alifa Nurani Putri
Teknik Informatika ITB 2011

**Comment by ichakid** [comment]
## KOSONG

[GET] .../tokobat-api/transactions?apotekId=100

Response:
{
    "transactions": [],
    "total": 0
}

## ISI

[GET] .../tokobat-api/transactions?apotekId=2

Response:
{
    "transactions": [
        {
            "transId": 8,
            "senderName": "Farrel",
            "read": false,
            "dateCreate": 1456077777794
        },
        {
            "transId": 9,
            "senderName": "Farrel",
            "read": false,
            "dateCreate": 1456077852124
        }
    ],
    "total": 2
}
