### ISSUE TITLE
Get All Apotek Location

### ISSUE THREAD

**Issue by ichakid** [CatalinaID/tokobat-api#6]
Request:
posisi (X)
radius (X)

Response:
List of apotek

**Comment by alifanuraniputri** [comment]
@hayyuelha @ichakid 

for small scale project, I propose that filtering apotek (based on radius) is on client side, Google Map Circle provides it easily. So we don't have to make API call every user update the circle size and point...

```
// Get the bounds
var bounds = circle.getBounds();
// Log into the dev bar console whether the marker is inside or outside
console.log( bounds.contains( latLngA ) );

```

[or try this](http://demo.developerextensions.com/answers/find-location-cordinates-in-given-radius.html)

so I will provide list Apotek with 

Respose: list Apotek

thank youu :3

**Comment by alifanuraniputri** [comment]
Request:

/tokobat-api/apotek/list

Response:

```
[
    {
        "address": null,
        "name": "Apotek Kampus",
        "id": 2,
        "lat": "-6.890577",
        "lng": "107.609859",
        "balance": null,
        "username": null,
        "message": null
    },
    {
        "address": null,
        "name": "Apotek K23",
        "id": 1,
        "lat": "-6.893858",
        "lng": "107.611189",
        "balance": null,
        "username": null,
        "message": null
    }
]
```
