### ISSUE TITLE
Get All Order

### ISSUE THREAD

**Issue by ichakid** [CatalinaID/tokobat-api#7]
Request:
msisdn

Response:
List of Order

**Comment by alifanuraniputri** [comment]
Contoh:

[GET] .../tokobat-api/transactions/listByUser?userId=1

Response:

[
    {
        "name": "obat alida",
        "id": 1,
        "total": 10000,
        "status": "1",
        "description": "test",
        "notes": "tidak ada",
        "readBy": true,
        "apotek": {
            "address": null,
            "name": "Apotek Ganesha",
            "id": 1,
            "hash": "b3894524eaf9809bd4f3ad2ff06fa4ab8d9251d3",
            "lat": "-6.89148",
            "lng": "107.6106591",
            "balance": 0,
            "dateCreate": 1454832325987,
            "username": "apotek_ganesha",
            "salt": "vmivkh8d3tbfnap12tq7kfdmtr"
        },
        "imgPath": "img",
        "dateCreate": 1454832406654,
        "user": {
            "name": "alifa",
            "id": 1,
            "msisdn": "081910355420",
            "dateCreate": 1454832406654,
            "uid": "357072061795934",
            "session": null
        },
        "apotekNotes": "coba"
    },
    {
        "name": "ss",
        "id": 2,
        "total": 11111,
        "status": "1",
        "description": "ss",
        "notes": "ss",
        "readBy": false,
        "apotek": {
            "address": null,
            "name": "Apotek Ganesha",
            "id": 1,
            "hash": "b3894524eaf9809bd4f3ad2ff06fa4ab8d9251d3",
            "lat": "-6.89148",
            "lng": "107.6106591",
            "balance": 0,
            "dateCreate": 1454832325987,
            "username": "apotek_ganesha",
            "salt": "vmivkh8d3tbfnap12tq7kfdmtr"
        },
        "imgPath": "ss",
        "dateCreate": 1454832406654,
        "user": {
            "name": "alifa",
            "id": 1,
            "msisdn": "081910355420",
            "dateCreate": 1454832406654,
            "uid": "357072061795934",
            "session": null
        },
        "apotekNotes": "dd"
    }
]
